//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace HistoryCube.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Stone_DBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Stone_DBEntities object using the connection string found in the 'Stone_DBEntities' section of the application configuration file.
        /// </summary>
        public Stone_DBEntities() : base("name=Stone_DBEntities", "Stone_DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Stone_DBEntities object.
        /// </summary>
        public Stone_DBEntities(string connectionString) : base(connectionString, "Stone_DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Stone_DBEntities object.
        /// </summary>
        public Stone_DBEntities(EntityConnection connection) : base(connection, "Stone_DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GroupRatioHistory> GroupRatioHistories
        {
            get
            {
                if ((_GroupRatioHistories == null))
                {
                    _GroupRatioHistories = base.CreateObjectSet<GroupRatioHistory>("GroupRatioHistories");
                }
                return _GroupRatioHistories;
            }
        }
        private ObjectSet<GroupRatioHistory> _GroupRatioHistories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GroupClusterHistory> GroupClusterHistories
        {
            get
            {
                if ((_GroupClusterHistories == null))
                {
                    _GroupClusterHistories = base.CreateObjectSet<GroupClusterHistory>("GroupClusterHistories");
                }
                return _GroupClusterHistories;
            }
        }
        private ObjectSet<GroupClusterHistory> _GroupClusterHistories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ClusterHistory> ClusterHistories
        {
            get
            {
                if ((_ClusterHistories == null))
                {
                    _ClusterHistories = base.CreateObjectSet<ClusterHistory>("ClusterHistories");
                }
                return _ClusterHistories;
            }
        }
        private ObjectSet<ClusterHistory> _ClusterHistories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GroupRateHistory> GroupRateHistories
        {
            get
            {
                if ((_GroupRateHistories == null))
                {
                    _GroupRateHistories = base.CreateObjectSet<GroupRateHistory>("GroupRateHistories");
                }
                return _GroupRateHistories;
            }
        }
        private ObjectSet<GroupRateHistory> _GroupRateHistories;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GroupRatioHistories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGroupRatioHistories(GroupRatioHistory groupRatioHistory)
        {
            base.AddObject("GroupRatioHistories", groupRatioHistory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GroupClusterHistories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGroupClusterHistories(GroupClusterHistory groupClusterHistory)
        {
            base.AddObject("GroupClusterHistories", groupClusterHistory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ClusterHistories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClusterHistories(ClusterHistory clusterHistory)
        {
            base.AddObject("ClusterHistories", clusterHistory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GroupRateHistories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGroupRateHistories(GroupRateHistory groupRateHistory)
        {
            base.AddObject("GroupRateHistories", groupRateHistory);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Stone_DBModel", Name="ClusterHistory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ClusterHistory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ClusterHistory object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="day">Initial value of the Day property.</param>
        /// <param name="clusterPrefix">Initial value of the ClusterPrefix property.</param>
        /// <param name="w">Initial value of the W property.</param>
        /// <param name="t">Initial value of the T property.</param>
        /// <param name="f">Initial value of the F property.</param>
        public static ClusterHistory CreateClusterHistory(global::System.Int32 id, global::System.Int32 day, global::System.Int32 clusterPrefix, global::System.Int32 w, global::System.Int32 t, global::System.Int32 f)
        {
            ClusterHistory clusterHistory = new ClusterHistory();
            clusterHistory.Id = id;
            clusterHistory.Day = day;
            clusterHistory.ClusterPrefix = clusterPrefix;
            clusterHistory.W = w;
            clusterHistory.T = t;
            clusterHistory.F = f;
            return clusterHistory;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Day
        {
            get
            {
                return _Day;
            }
            set
            {
                OnDayChanging(value);
                ReportPropertyChanging("Day");
                _Day = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Day");
                OnDayChanged();
            }
        }
        private global::System.Int32 _Day;
        partial void OnDayChanging(global::System.Int32 value);
        partial void OnDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClusterPrefix
        {
            get
            {
                return _ClusterPrefix;
            }
            set
            {
                OnClusterPrefixChanging(value);
                ReportPropertyChanging("ClusterPrefix");
                _ClusterPrefix = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClusterPrefix");
                OnClusterPrefixChanged();
            }
        }
        private global::System.Int32 _ClusterPrefix;
        partial void OnClusterPrefixChanging(global::System.Int32 value);
        partial void OnClusterPrefixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 W
        {
            get
            {
                return _W;
            }
            set
            {
                OnWChanging(value);
                ReportPropertyChanging("W");
                _W = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("W");
                OnWChanged();
            }
        }
        private global::System.Int32 _W;
        partial void OnWChanging(global::System.Int32 value);
        partial void OnWChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 T
        {
            get
            {
                return _T;
            }
            set
            {
                OnTChanging(value);
                ReportPropertyChanging("T");
                _T = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("T");
                OnTChanged();
            }
        }
        private global::System.Int32 _T;
        partial void OnTChanging(global::System.Int32 value);
        partial void OnTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 F
        {
            get
            {
                return _F;
            }
            set
            {
                OnFChanging(value);
                ReportPropertyChanging("F");
                _F = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("F");
                OnFChanged();
            }
        }
        private global::System.Int32 _F;
        partial void OnFChanging(global::System.Int32 value);
        partial void OnFChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Stone_DBModel", Name="GroupClusterHistory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GroupClusterHistory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GroupClusterHistory object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="day">Initial value of the Day property.</param>
        /// <param name="groupNumber">Initial value of the GroupNumber property.</param>
        /// <param name="clusterPrefix">Initial value of the ClusterPrefix property.</param>
        public static GroupClusterHistory CreateGroupClusterHistory(global::System.Int32 id, global::System.Int32 day, global::System.Int32 groupNumber, global::System.Int32 clusterPrefix)
        {
            GroupClusterHistory groupClusterHistory = new GroupClusterHistory();
            groupClusterHistory.Id = id;
            groupClusterHistory.Day = day;
            groupClusterHistory.GroupNumber = groupNumber;
            groupClusterHistory.ClusterPrefix = clusterPrefix;
            return groupClusterHistory;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Day
        {
            get
            {
                return _Day;
            }
            set
            {
                OnDayChanging(value);
                ReportPropertyChanging("Day");
                _Day = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Day");
                OnDayChanged();
            }
        }
        private global::System.Int32 _Day;
        partial void OnDayChanging(global::System.Int32 value);
        partial void OnDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupNumber
        {
            get
            {
                return _GroupNumber;
            }
            set
            {
                OnGroupNumberChanging(value);
                ReportPropertyChanging("GroupNumber");
                _GroupNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupNumber");
                OnGroupNumberChanged();
            }
        }
        private global::System.Int32 _GroupNumber;
        partial void OnGroupNumberChanging(global::System.Int32 value);
        partial void OnGroupNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClusterPrefix
        {
            get
            {
                return _ClusterPrefix;
            }
            set
            {
                OnClusterPrefixChanging(value);
                ReportPropertyChanging("ClusterPrefix");
                _ClusterPrefix = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClusterPrefix");
                OnClusterPrefixChanged();
            }
        }
        private global::System.Int32 _ClusterPrefix;
        partial void OnClusterPrefixChanging(global::System.Int32 value);
        partial void OnClusterPrefixChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Stone_DBModel", Name="GroupRateHistory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GroupRateHistory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GroupRateHistory object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="day">Initial value of the Day property.</param>
        /// <param name="groupNumber">Initial value of the GroupNumber property.</param>
        /// <param name="rate">Initial value of the Rate property.</param>
        public static GroupRateHistory CreateGroupRateHistory(global::System.Int32 id, global::System.Int32 day, global::System.Int32 groupNumber, global::System.Int32 rate)
        {
            GroupRateHistory groupRateHistory = new GroupRateHistory();
            groupRateHistory.Id = id;
            groupRateHistory.Day = day;
            groupRateHistory.GroupNumber = groupNumber;
            groupRateHistory.Rate = rate;
            return groupRateHistory;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Day
        {
            get
            {
                return _Day;
            }
            set
            {
                OnDayChanging(value);
                ReportPropertyChanging("Day");
                _Day = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Day");
                OnDayChanged();
            }
        }
        private global::System.Int32 _Day;
        partial void OnDayChanging(global::System.Int32 value);
        partial void OnDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupNumber
        {
            get
            {
                return _GroupNumber;
            }
            set
            {
                OnGroupNumberChanging(value);
                ReportPropertyChanging("GroupNumber");
                _GroupNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupNumber");
                OnGroupNumberChanged();
            }
        }
        private global::System.Int32 _GroupNumber;
        partial void OnGroupNumberChanging(global::System.Int32 value);
        partial void OnGroupNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Rate
        {
            get
            {
                return _Rate;
            }
            set
            {
                OnRateChanging(value);
                ReportPropertyChanging("Rate");
                _Rate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rate");
                OnRateChanged();
            }
        }
        private global::System.Int32 _Rate;
        partial void OnRateChanging(global::System.Int32 value);
        partial void OnRateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Stone_DBModel", Name="GroupRatioHistory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GroupRatioHistory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GroupRatioHistory object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="day">Initial value of the Day property.</param>
        /// <param name="groupNumber">Initial value of the GroupNumber property.</param>
        /// <param name="ratio">Initial value of the Ratio property.</param>
        public static GroupRatioHistory CreateGroupRatioHistory(global::System.Int32 id, global::System.Int32 day, global::System.Int32 groupNumber, global::System.Int32 ratio)
        {
            GroupRatioHistory groupRatioHistory = new GroupRatioHistory();
            groupRatioHistory.Id = id;
            groupRatioHistory.Day = day;
            groupRatioHistory.GroupNumber = groupNumber;
            groupRatioHistory.Ratio = ratio;
            return groupRatioHistory;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Day
        {
            get
            {
                return _Day;
            }
            set
            {
                OnDayChanging(value);
                ReportPropertyChanging("Day");
                _Day = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Day");
                OnDayChanged();
            }
        }
        private global::System.Int32 _Day;
        partial void OnDayChanging(global::System.Int32 value);
        partial void OnDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupNumber
        {
            get
            {
                return _GroupNumber;
            }
            set
            {
                OnGroupNumberChanging(value);
                ReportPropertyChanging("GroupNumber");
                _GroupNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupNumber");
                OnGroupNumberChanged();
            }
        }
        private global::System.Int32 _GroupNumber;
        partial void OnGroupNumberChanging(global::System.Int32 value);
        partial void OnGroupNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Ratio
        {
            get
            {
                return _Ratio;
            }
            set
            {
                OnRatioChanging(value);
                ReportPropertyChanging("Ratio");
                _Ratio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ratio");
                OnRatioChanged();
            }
        }
        private global::System.Int32 _Ratio;
        partial void OnRatioChanging(global::System.Int32 value);
        partial void OnRatioChanged();

        #endregion

    
    }

    #endregion

    
}
